### ISSUE TITLE
Mdx and Attribute filtering

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/mdxpy#1]
#1 this is an awesome addition to the TM1 toolkit, so thank you, I am excited to contribute.

#2 admittedly this is a bit of a blind spot for me but  I wonder what is the "best" way to do attribute filtering. I have used all 3 ways in the past, but I don't know why you would use one over the others. Do you have any insight? 

`{FILTER({TM1SUBSETALL([Product] )}, [Product].[Product]. [Category]="Skis")}`

`{FILTER({TM1SUBSETALL( [Product] )}, [Product].[Product].Properties('Category')="Skis")}`

`{FILTER({TM1SUBSETALL([Product] )}, [Product].[}ElementAttributes_Product].([}ElementAttributes_Product].[}ElementAttributes_Product].[Category]) ="Skis")}`

**Comment by scrumthing** [comment]
I like that new project as well. Huge potential here!
@rclapp I would guess that of your three examples 1 and 2 are just the same if you are looking at speed of execution. 1 is just the abbreviation of 2 but technically the same. And of course it is the proper way of filtering in other MDX interpretations (i.e. MSAS). Any contradicting thoughts on that?
Number 3 would be a way that only works in TM1 and only works as long as attributes are viewed as data. (Don’t get Hubert startet on that!) So I would recommend to use 1 or 2. Personally I would (almost) always go for the longer versions. But that is just because I hate abbreviations (and had some bad experiences with it and TM1 in the past).
^^my two cents...

A bit of topic but somehow related to your questions: Should mdxpy only use generic MDX or include TM1 specific functions (i.e. TM1SubsetAll()) as well? I would prefer the generic approach because that way you could potentially fork it for other databases more easily and the TM1 specific functions are AFAIK more or less deprecated. Any thoughts on that?

**Comment by MariusWirtz** [comment]
@rclapp
Thank you! Looking forward to your MR ;-)

The first one is problematic due to potential name conflicts with existing elements.
The second one doesn't work well with numeric attributes.
The third one is overly verbose but it's the safest IMO.

@scrumthing
Thank you! I agree we should support other dialects of MDX as well.
My initial idea was that when you call the `to_mdx` method you could pass the dialect as an argument.

``` python
>>> query = MdxBuilder.from_cube("Cube").add_hierarchy_set_to_column_axis(MdxHierarchySet.member(Member.of("Product", "Product1")))
>>> print(query.to_mdx(dialect="TM1"))
SELECT 
{[PRODUCT].[PRODUCT].[PRODUCT1]} ON 0
FROM [CUBE] 

```
It would then fail if you use TM1 specific MDX functions and try to generate Microsoft MDX.

**Comment by MariusWirtz** [comment]
@scrumthing
I think it would be nice, but I am not sure if we can keep everything generic. I think not all TM1 specific functions can be substituted by their generic equivalents.
I mean `{Tm1SubsetAll([Dimension])}` is not the same as `{[Dimension].Members}` etc.

**Comment by scrumthing** [comment]
Yes. TM1 is at the moment in a situation where it behaves like other multidimensional databases (i.e. MSAS) and in others it is not. The TM1SubsetAll is a prime example of this. But we should try to first find a generic approach and only refer to the TM1 specific functions if really no other suitable solution is possible. 
One of my favourite problems with TM1 and MDX btw. is “spaces”. TM1 itself (i.e. Rules and TI) does not care about them. But if you use MDX suddenly this becomes an issue. 

For the record: I do not use and do not advice to use spaces anywhere in element names or process or views... On the contrary I strongly advise to NOT DO IT! ;-)

**Comment by rclapp** [comment]
TM1 is never case or space sensitive, even in MDX, where have you seen otherwise? In my opinion, when building TM1 models you should always match the business venacular to make the element names meaningful and easy to read, includeing space.

`{[Scenario].[Scenario].[Act ual]}` returns the same thing as `{[Scenario].[Scenario].[Actual]}` and the same thing as {[Scenario].[Scenario].[AcTual]}

When it comes to MDX functions vs TM1 functions, some of them are simply built as work arounds to common MDX problems. TM1SubsetAll for example returns to you the first instance of an element name, where .Members returns unique members where [Net Income ^Margin] is a different member from [Net Income^Margin Percent]. I view the TM1 functions not as something that should be avoided, but as something that provides a fix for issues with normal MDX. Even with hierarchies there are plenty of cases where an element name appears multiple times in a hierarchy, without the TM1SubsetAll function it would be very hard to get a subset of unique elements (not members).

**Comment by scrumthing** [comment]
@rclapp There are cases when TM1 makes a difference. For example if you use TM1FilterByPattern spaces become an issue (see attached screenshot). 
![image](https://user-images.githubusercontent.com/8442014/81274198-41909800-9050-11ea-867f-36c76740a48e.png)
As well if you try to order your processes in a specific way you get a result which is space sensitive. 
![Uploading image.png…]()
And finally in architect objects are ordered differently if there are spaces in their name.

**Comment by rclapp** [comment]
For sure, filter by pattern is a bit different since it gives you wild cards for single and multi-character strings. That function certainly doesn’t follow the “TM1 Norms”

On object ordering, that is purely a UI issue. It would be nice if the UI matched TM1’s internal treatment of objects but thankfully Architect is on its way out.

Thanks,

Ryan Clapp

**Comment by scrumthing** [comment]
Yes. That is the point I am trying to make. :-) In some cases spaces are treated differently and to avoid issues I would recommend to never use them in object names. Same goes for special characters. If you have to use some of them. At least put them into an alias. I find Scotts blog post on naming conventions very helpful: [Cubewise Blog](https://cubewise.com/blog/naming-convention-rules-object-element-attribute/)
He mentions another point there. The REST API is case and space sensitive. 
 Anyway that is a very interesting discussion with a lot of other points as well. But I am not sure if that is the right place for the discussion. :-)
